# Generated by Django 4.2.7 on 2023-11-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_rename_project_photo_pet_alter_pet_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='end_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='start_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
