# Generated by Django 4.2.7 on 2023-11-07 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_adoption_end_at_alter_adoption_start_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='pets.pet'),
        ),
    ]
