# Generated by Django 4.2.7 on 2023-11-12 04:21

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0004_alter_adoption_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pet',
            unique_together={('owner', 'name', 'birthdate')},
        ),
    ]
