# Generated by Django 4.2.7 on 2023-11-12 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_pet_birthdate_alter_pet_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birthdate',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
