# Generated by Django 4.2.7 on 2023-11-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_pet_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_type',
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Turtle', 'Turtle'), ('Hamster', 'Hamster')], max_length=10, null=True),
        ),
    ]
