# Generated by Django 4.2.7 on 2023-11-18 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_remove_pet_pet_type_pet_breed_alter_pet_species'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='pet',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Turtle', 'Turtle'), ('Hamster', 'Hamster'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
