# Generated by Django 4.2.7 on 2023-11-05 23:00

from django.db import migrations, models
import django.db.models.deletion
# -------------------------------------

# from django.db.models import F

# def set_default_user(apps, schema_editor):
#     User = apps.User('accounts', 'User')  # Adjust the app and model name accordingly
#     Post = apps.Post('social', 'Post')  # Replace with your actual app and model name
#     Post.objects.update(user=F('user') or User.objects.first())


# ------------------------------------------------

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='social.post')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projects/images/%Y/%m/%d/%H/%M/%S/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='social.post')),
            ],
        ),
    ]
