# Generated by Django 4.2.7 on 2023-11-19 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_photo_photo_alter_post_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
