# Generated by Django 4.2.7 on 2023-11-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created_at']},
        ),
    ]
