# Generated by Django 4.2.7 on 2023-11-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_alter_report_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created_at']},
        ),
    ]
