# Generated by Django 4.2.7 on 2023-11-05 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdoptRequest',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
