# Generated by Django 4.2.7 on 2023-11-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptrequest',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
