# Generated by Django 4.2.7 on 2023-11-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_adoptrequest_created_at_alter_offer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
