# Generated by Django 4.2.7 on 2023-11-10 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('offers', '0006_rename_message_offer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptrequest',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chats.message'),
        ),
    ]
