# Generated by Django 4.2.7 on 2023-11-12 04:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0005_alter_pet_birthdate_alter_pet_unique_together'),
        ('offers', '0007_alter_adoptrequest_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adoptrequest',
            unique_together={('user', 'offer')},
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('user', 'pet')},
        ),
    ]
