# Generated by Django 4.2.7 on 2023-11-12 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_alter_adoptrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='available',
        ),
    ]
