# Generated by Django 4.2.7 on 2023-11-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_remove_offer_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
