# Generated by Django 4.2.7 on 2023-11-16 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_message_created_at'),
        ('offers', '0010_alter_offer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptrequest',
            name='message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.message'),
        ),
    ]
